name = "AlecRegistry"
uuid = "0938e7e9-6a13-42a2-b721-e529281cb023"
repo = "https://github.com/abillscmu/AlecRegistry"
description = "The official private registry of alec"

[packages]
3496906c-a3e1-4a4f-8055-83ed9b3a7d55 = { name = "MATLABPlots", path = "M/MATLABPlots" }
